### ISSUE TITLE
Dashborad does not show logs in grafana 8.1.1 

### ISSUE THREAD

**Issue by SaymonDzen** [lux4rd0/grafana-loki-syslog-aio#6]
Launched a new instance and did not see the logs. Checking the dump showed that the logs are coming. I changed the tag to 7.5.10 for grafana and everything began to be displayed. The problem with the latest tagged container 
![grafana 8](https://user-images.githubusercontent.com/46021442/129167424-6fcfba82-23aa-45b9-ba5b-f3732315bdbd.PNG)

**Comment by lux4rd0** [comment]
Thanks for the message @SaymonDzen - I'll take a look at the dashboard and see what's changed between Grafana 7.5 and Grafana 8. Probably time for a refresh of all of those components anyway! :)

**Comment by lux4rd0** [comment]
@SaymonDzen, I just updated the project to work with Grafana 8.1.2. I also updated all of the dashboards to the new Grafana Time series visualization. This specific error was coming from a change in the Loki variables. Again - thanks for sharing with me that it was no longer working.
